// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/integral.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_COMPOSITE_SIMPSON Method = 0
	Method_ADAPTIVE_SIMPSON  Method = 1
	Method_GAUSS_KRONROD     Method = 2
	Method_HYBRID_AUTO       Method = 3
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "COMPOSITE_SIMPSON",
		1: "ADAPTIVE_SIMPSON",
		2: "GAUSS_KRONROD",
		3: "HYBRID_AUTO",
	}
	Method_value = map[string]int32{
		"COMPOSITE_SIMPSON": 0,
		"ADAPTIVE_SIMPSON":  1,
		"GAUSS_KRONROD":     2,
		"HYBRID_AUTO":       3,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_integral_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_proto_integral_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_proto_integral_proto_rawDescGZIP(), []int{0}
}

type IntegralRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function string  `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	A        float64 `protobuf:"fixed64,2,opt,name=a,proto3" json:"a,omitempty"`
	B        float64 `protobuf:"fixed64,3,opt,name=b,proto3" json:"b,omitempty"`
	N        int32   `protobuf:"varint,4,opt,name=n,proto3" json:"n,omitempty"`
	Method   Method  `protobuf:"varint,5,opt,name=method,proto3,enum=integral.Method" json:"method,omitempty"`
	Epsilon  float64 `protobuf:"fixed64,6,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
}

func (x *IntegralRequest) Reset() {
	*x = IntegralRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_integral_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntegralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegralRequest) ProtoMessage() {}

func (x *IntegralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integral_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegralRequest.ProtoReflect.Descriptor instead.
func (*IntegralRequest) Descriptor() ([]byte, []int) {
	return file_proto_integral_proto_rawDescGZIP(), []int{0}
}

func (x *IntegralRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *IntegralRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *IntegralRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *IntegralRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *IntegralRequest) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_COMPOSITE_SIMPSON
}

func (x *IntegralRequest) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

type IntegralResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *IntegralResponse) Reset() {
	*x = IntegralResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_integral_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntegralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegralResponse) ProtoMessage() {}

func (x *IntegralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integral_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegralResponse.ProtoReflect.Descriptor instead.
func (*IntegralResponse) Descriptor() ([]byte, []int) {
	return file_proto_integral_proto_rawDescGZIP(), []int{1}
}

func (x *IntegralResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *IntegralResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_integral_proto protoreflect.FileDescriptor

var file_proto_integral_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c,
	0x22, 0x8e, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x61, 0x12, 0x0c,
	0x0a, 0x01, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e, 0x12, 0x27, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x6c, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x70, 0x73, 0x69, 0x6c, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x65, 0x70, 0x73, 0x69, 0x6c, 0x6f, 0x6e, 0x22, 0x3f,
	0x0a, 0x10, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x2a, 0x37, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f,
	0x4d, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x45, 0x5f, 0x53, 0x49, 0x4d, 0x50, 0x53, 0x4f, 0x4e, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x44, 0x41, 0x50, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x53, 0x49,
	0x4d, 0x50, 0x53, 0x4f, 0x4e, 0x10, 0x01, 0x32, 0x54, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x10, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12,
	0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x6c, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_integral_proto_rawDescOnce sync.Once
	file_proto_integral_proto_rawDescData = file_proto_integral_proto_rawDesc
)

func file_proto_integral_proto_rawDescGZIP() []byte {
	file_proto_integral_proto_rawDescOnce.Do(func() {
		file_proto_integral_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_integral_proto_rawDescData)
	})
	return file_proto_integral_proto_rawDescData
}

var file_proto_integral_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_integral_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_integral_proto_goTypes = []interface{}{
	(Method)(0),               // 0: integral.Method
	(*IntegralRequest)(nil),   // 1: integral.IntegralRequest
	(*IntegralResponse)(nil),  // 2: integral.IntegralResponse
}
var file_proto_integral_proto_depIdxs = []int32{
	0, // 0: integral.IntegralRequest.method:type_name -> integral.Method
	1, // 1: integral.IntegralService.CalculateIntegral:input_type -> integral.IntegralRequest
	2, // 2: integral.IntegralService.CalculateIntegral:output_type -> integral.IntegralResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_integral_proto_init() }
func file_proto_integral_proto_init() {
	if File_proto_integral_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_integral_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntegralRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_integral_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntegralResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_integral_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_integral_proto_goTypes,
		DependencyIndexes: file_proto_integral_proto_depIdxs,
		EnumInfos:         file_proto_integral_proto_enumTypes,
		MessageInfos:      file_proto_integral_proto_msgTypes,
	}.Build()
	File_proto_integral_proto = out.File
	file_proto_integral_proto_rawDesc = nil
	file_proto_integral_proto_goTypes = nil
	file_proto_integral_proto_depIdxs = nil
}
