// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// protoc-gen-go-grpc v1.3.0
// source: proto/integral.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IntegralServiceClient is the client API for IntegralService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegralServiceClient interface {
	CalculateIntegral(ctx context.Context, in *IntegralRequest, opts ...grpc.CallOption) (*IntegralResponse, error)
}

type integralServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegralServiceClient(cc grpc.ClientConnInterface) IntegralServiceClient {
	return &integralServiceClient{cc}
}

func (c *integralServiceClient) CalculateIntegral(ctx context.Context, in *IntegralRequest, opts ...grpc.CallOption) (*IntegralResponse, error) {
	out := new(IntegralResponse)
	err := c.cc.Invoke(ctx, "/integral.IntegralService/CalculateIntegral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegralServiceServer is the server API for IntegralService service.
// All implementations must embed UnimplementedIntegralServiceServer for forward compatibility.
type IntegralServiceServer interface {
	CalculateIntegral(context.Context, *IntegralRequest) (*IntegralResponse, error)
	mustEmbedUnimplementedIntegralServiceServer()
}

// UnimplementedIntegralServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntegralServiceServer struct {
}

func (UnimplementedIntegralServiceServer) CalculateIntegral(context.Context, *IntegralRequest) (*IntegralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateIntegral not implemented")
}
func (UnimplementedIntegralServiceServer) mustEmbedUnimplementedIntegralServiceServer() {}

// UnsafeIntegralServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegralServiceServer will result in compilation errors.
type UnsafeIntegralServiceServer interface {
	mustEmbedUnimplementedIntegralServiceServer()
}

func RegisterIntegralServiceServer(s grpc.ServiceRegistrar, srv IntegralServiceServer) {
	s.RegisterService(&IntegralService_ServiceDesc, srv)
}

func _IntegralService_CalculateIntegral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegralServiceServer).CalculateIntegral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integral.IntegralService/CalculateIntegral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegralServiceServer).CalculateIntegral(ctx, req.(*IntegralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegralService_ServiceDesc is the grpc.ServiceDesc for IntegralService service.
// It's only intended for direct use with grpc.RegisterService, and not to be introspected or modified (even as a copy)
var IntegralService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integral.IntegralService",
	HandlerType: (*IntegralServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateIntegral",
			Handler:    _IntegralService_CalculateIntegral_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/integral.proto",
}
